### ISSUE TITLE
Stuck on "diarizing"

### ISSUE THREAD

**Issue by bouiboui** [audapolis/audapolis#226] opened 2022-01-13 14:50 UTC
Hi, I'm trying audapolis on Windows 10, the install and download of models went fine, but I'm stuck when I try to transcribe a file:

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/3274103/149349953-fa7c7f35-89ea-453d-81fc-57f2bfe0951e.png)

</details>

I'm getting these errors in the console, not sure if related:

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/3274103/149350155-a1b8cbb6-a116-4124-be09-bf607d5b9e70.png)

</details>

The line that throws an error seems unrelated, but here's the last `server stderr`:

<details>
<summary>Here's the log</summary>

```
ERROR:    Exception in ASGI application
 Traceback (most recent call last):
   File "uvicorn.protocols.http.httptools_impl", line 375, in run_asgi
     result = await app(self.scope, self.receive, self.send)
   File "uvicorn.middleware.proxy_headers", line 75, in __call__
     return await self.app(scope, receive, send)
   File "fastapi.applications", line 208, in __call__
     await super().__call__(scope, receive, send)
   File "starlette.applications", line 112, in __call__
     await self.middleware_stack(scope, receive, send)
   File "starlette.middleware.errors", line 181, in __call__
     raise exc from None
   File "starlette.middleware.errors", line 159, in __call__
     await self.app(scope, receive, _send)
   File "starlette.middleware.cors", line 78, in __call__
     await self.app(scope, receive, send)
   File "starlette.exceptions", line 82, in __call__
     raise exc from None
   File "starlette.exceptions", line 71, in __call__
     await self.app(scope, receive, sender)
   File "starlette.routing", line 580, in __call__
     await route.handle(scope, receive, send)
   File "starlette.routing", line 241, in handle
     await self.app(scope, receive, send)
   File "starlette.routing", line 55, in app
     await response(scope, receive, send)
   File "starlette.responses", line 146, in __call__
     await self.background()
   File "starlette.background", line 35, in __call__
     await task()
   File "starlette.background", line 20, in __call__
     await run_in_threadpool(self.func, *self.args, **self.kwargs)
   File "starlette.concurrency", line 40, in run_in_threadpool
     return await loop.run_in_executor(None, func, *args)
   File "concurrent.futures.thread", line 52, in run
     result = self.fn(*self.args, **self.kwargs)
   File "app.transcribe", line 101, in process_audio
     segments = diarization_model.diarize(
   File "pydiar.models.binary_key", line 241, in diarize
     best_clustering = self._binary_processing(
   File "pydiar.models.binary_key", line 153, in _binary_processing
     finalClusteringTable, k = performClustering(
   File "pydiar.models.binary_key.diarizationFunctions", line 297, in performClustering
     location = np.nanargmax(clusterSimilarityMatrix)
   File "<__array_function__ internals>", line 5, in nanargmax
   File "numpy.lib.nanfunctions", line 549, in nanargmax
     raise ValueError("All-NaN slice encountered")
 ValueError: All-NaN slice encountered
 ERROR:uvicorn.error:Exception in ASGI application
 Traceback (most recent call last):
   File "uvicorn.protocols.http.httptools_impl", line 375, in run_asgi
     result = await app(self.scope, self.receive, self.send)
   File "uvicorn.middleware.proxy_headers", line 75, in __call__
     return await self.app(scope, receive, send)
   File "fastapi.applications", line 208, in __call__
     await super().__call__(scope, receive, send)
   File "starlette.applications", line 112, in __call__
     await self.middleware_stack(scope, receive, send)
   File "starlette.middleware.errors", line 181, in __call__
     raise exc from None
   File "starlette.middleware.errors", line 159, in __call__
     await self.app(scope, receive, _send)
   File "starlette.middleware.cors", line 78, in __call__
     await self.app(scope, receive, send)
   File "starlette.exceptions", line 82, in __call__
     raise exc from None
   File "starlette.exceptions", line 71, in __call__
     await self.app(scope, receive, sender)
   File "starlette.routing", line 580, in __call__
     await route.handle(scope, receive, send)
   File "starlette.routing", line 241, in handle
     await self.app(scope, receive, send)
   File "starlette.routing", line 55, in app
     await response(scope, receive, send)
   File "starlette.responses", line 146, in __call__
     await self.background()
   File "starlette.background", line 35, in __call__
     await task()
   File "starlette.background", line 20, in __call__
     await run_in_threadpool(self.func, *self.args, **self.kwargs)
   File "starlette.concurrency", line 40, in run_in_threadpool
     return await loop.run_in_executor(None, func, *args)
   File "concurrent.futures.thread", line 52, in run
     result = self.fn(*self.args, **self.kwargs)
   File "app.transcribe", line 101, in process_audio
     segments = diarization_model.diarize(
   File "pydiar.models.binary_key", line 241, in diarize
     best_clustering = self._binary_processing(
   File "pydiar.models.binary_key", line 153, in _binary_processing
     finalClusteringTable, k = performClustering(
   File "pydiar.models.binary_key.diarizationFunctions", line 297, in performClustering
     location = np.nanargmax(clusterSimilarityMatrix)
   File "<__array_function__ internals>", line 5, in nanargmax
   File "numpy.lib.nanfunctions", line 549, in nanargmax
     raise ValueError("All-NaN slice encountered")
 ValueError: All-NaN slice encountered
```

</details>

Thanks for your help.

**Comment by anuejn** [comment] 2022-01-13 17:20
Thank you for reporting that issue. we will look into this :)

**Comment by pajowu** [comment] 2022-01-13 23:18
Hey @bouiboui , thank's for raising this issue. On first glance it looks like you're trying to transcribe a file where the system thinks there is no speech (but only music for example). I will prepare a fix for that, but could you maybe give us access to the file you're using to I can verify this? If yes, you could send it to audapolis@pajowu.de

**Comment by bouiboui** [comment] 2022-01-13 23:42
Thanks for the quick answers!
It's not a private file, you can download it from here: https://fromsmash.com/at7~OAwTa--ct

**Comment by pajowu** [comment] 2022-01-14 00:34
Thanks for the file. I think I identified (at least one) issue with the diarization that could cause this. I fixed it in https://github.com/audapolis/pydiar/pull/4 and will update audapolis once that landed

**Comment by bouiboui** [comment] 2022-01-14 05:35
That's amazing 👍 Thank you.

**Comment by jgarplind** [comment] 2022-01-14 08:53
Great! I ran into something similar but was not able to reproduce reliably.

**Closed** 2022-02-13 14:08 UTC
Labels: bug
